/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  skycons.play();
  
  // want to change the icon? no problem:
  
/*
Get value from Bootstrap dropdown menu
*/
var citylist =[ '臺北市',
                '新北市',
                '台中市',
                '臺南市',
                '高雄市',
                '基隆市',
                '桃園區',
                '新竹市',
                '新竹縣',
                '苗栗縣',
                '彰化縣',
                '南投縣',
                '雲林縣',
                '嘉義市',
                '嘉義縣',
                '屏東縣',
                '宜蘭縣',
                '花蓮縣',
                '台東縣',
                '澎湖縣',
                '金門縣',
                '連江縣' ];

var city="Taipei";

var citychoose = function(){
  $('.btn').text(citylist[0]);
  $('li').remove();
  for(var i=0;i<citylist.length;i+=1){
  $('<li role="presentation"><a role="menuitem" tabindex="-1" href="#">'+citylist[i]+'</a></li>').appendTo('#dropdown');
   }
 };

citychoose();

$('#dropdown li').on('click', function(){
  city = ($(this).text());
  $('.btn').text($(this).text());  
  getweather();
});

var getweather = function(){
$.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+city+'") and u="c"',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel.item,
           weather =[
          todayweather ={  date : weatherInfo.forecast[0].date,
                            code : weatherInfo.forecast[0].code,
                            high : weatherInfo.forecast[0].high,
                            low  : weatherInfo.forecast[0].low,
                            text  : weatherInfo.forecast[0].text },

                 Day1 ={   date : weatherInfo.forecast[1].date,
                            code : weatherInfo.forecast[1].code,
                            high : weatherInfo.forecast[1].high,
                            low  : weatherInfo.forecast[1].low,
                            text  : weatherInfo.forecast[1].text },

                 Day2 ={   date : weatherInfo.forecast[2].date,
                            code : weatherInfo.forecast[2].code,
                            high : weatherInfo.forecast[2].high,
                            low  : weatherInfo.forecast[2].low,
                            text  : weatherInfo.forecast[2].text },

                 Day3 ={   date : weatherInfo.forecast[3].date,
                            code : weatherInfo.forecast[3].code,
                            high : weatherInfo.forecast[3].high,
                            low  : weatherInfo.forecast[3].low,
                            text  : weatherInfo.forecast[3].text }];

          $('#todaytCondition').text(todayweather.text);
          $('.date').text(todayweather.date);
          $('#day1Date').text(Day1.date);
          $('#day2Date').text(Day2.date);
          $('#day3Date').text(Day3.date);

          $('#day1Tem').text(Day1.low+"-"+Day1.high+ "℃");
          $('#day2Tem').text(Day2.low+"-"+Day2.high+ "℃");
          $('#day3Tem').text(Day3.low+"-"+Day3.high+ "℃");

      var changeSkycon = function(){
          for(var i =0;i<weather.length;i+=1){
            var conditioncode = weather[i].code;
            var date =["today","day1","day2","day3"];
            if (conditioncode===(32||34||36)) {
              skycons.set(date[i], Skycons.CLEAR_DAY);
            }else if(conditioncode===(31||33)){
              skycons.set(date[i], Skycons.CLEAR_NIGHT);
            }else if(conditioncode===(28||30)){
              skycons.set(date[i], Skycons.PARTLY_CLOUDY_DAY);
            }else if(conditioncode===(27||29)){
              skycons.set(date[i], Skycons.PARTLY_CLOUDY_NIGHT);
            }else if(conditioncode===(25||26||44)){
              skycons.set(date[i], Skycons.CLOUDY);
            }else if((3<=conditioncode && conditioncode<=10)||(conditioncode===35)){
              skycons.set(date[i], Skycons.RAIN);
            }else if((37<=conditioncode && conditioncode<=40)||(conditioncode===(11||12||45||47))){
              skycons.set(date[i], Skycons.SLEET);
            }
         };
       };
       changeSkycon();
     }
   });

};
getweather();
  


  
